[package]
name = "xml-to-postgres"
version = "0.1.0"
authors = ["Bart Noordervliet"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.18"
yaml-rust = "0.4"
