[package]
name = "xml-to-postgres"
version = "1.0.0"
authors = ["Bart Noordervliet <bart@mmvi.nl>"]
edition = "2021"
description = "Fast converter from XML to PostgreSQL dump format"
publish = false

[dependencies]
quick-xml = "0.22"
yaml-rust = "0.4"
regex = "1"
lazy_static = "1"
